# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Etareduce
email: etareduce@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Mostly writings about programing, tech, and life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jiayul.me" # the base hostname & protocol for your site
twitter_username: Jimexist
github_username:  Jimexist

# Build settings
markdown: kramdown
